apiVersion: v2
name: my-cluster
description: A Helm chart for my Kubernetes cluster
version: 0.1.0
dependencies:
  - name: essential
    version: 0.1.0
    condition: essential.enabled
  - name: monitoring
    version: 0.1.0
    condition: monitoring.enabled
  - name: network
    version: 0.1.0
    condition: network.enabled
  - name: security
    version: 0.1.0
    condition: security.enabled
  - name: istio
    version: 0.1.0
    condition: istio.enabled
