apiVersion: v2
name: certification
description: A Helm chart for Kubernetes
icon: https://helm.elastic.co/icons/eck.png
version: 0.1.0

dependencies:
  - name: cert-manager
    version: 1.16.1
    repository: https://charts.jetstack.io
    weight: 0
    condition: cert-manager.enabled
  - name: vault
    version: 0.29.0
    repository: https://helm.releases.hashicorp.com
    weight: 1
    condition: vault.enabled

