apiVersion: v2
name: monitoring
description: monitoring
version: 0.1.0
icon: https://helm.elastic.co/icons/eck.png

dependencies:
  - name: grafana
    version: 8.6.0
    repository: https://grafana.github.io/helm-charts
    weight: 4
    condition: grafana.enabled
  - name: prometheus
    version: 25.30.0
    repository: https://prometheus-community.github.io/helm-charts
    weight: 4
    condition: prometheus.enabled